name: monthly

on:
  schedule:
    - cron: "0 6 1 * *"  # Scheduled to run at 6AM on 1st day of every month
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt


      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libgconf-2-4 \
            libxss1 \
            libappindicator1 \
            libindicator7 \
            libasound2 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            xdg-utils \
            wget \
            libgbm1 \
            libu2f-udev \
            libvulkan1

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Remove the Install Chromedriver step as it's handled by webdriver-manager

      - name: Install language fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming \
                                fonts-ipafont-mincho fonts-ipafont-gothic \
                                fonts-unfonts-core fonts-noto-cjk \
                                fonts-kacst fonts-kacst-one fonts-arabeyes \
                                fonts-sil-scheherazade ttf-wqy-zenhei
          sudo fc-cache -fv

      - name: Run Python Script
        run: python app.py

      - name: Check OpenSSL Version
      run: |
        python -c "import ssl; print(ssl.OPENSSL_VERSION)"
