name: monthly

on:
  schedule:
    - cron: "0 6 1 * *"  # Scheduled to run at 6AM on 1st day of every month
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Specifies the runner environment
    timeout-minutes: 360

    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v3  # Checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up Python environment
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libgconf-2-4 \
            libxss1 \
            libappindicator1 \
            libindicator7 \
            libasound2 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            xdg-utils \
            wget \
            libgbm1 \
            libu2f-udev \
            libvulkan1

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install language fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming \
                                fonts-ipafont-mincho fonts-ipafont-gothic \
                                fonts-unfonts-core fonts-noto-cjk \
                                fonts-kacst fonts-kacst-one fonts-arabeyes \
                                fonts-sil-scheherazade ttf-wqy-zenhei
          sudo fc-cache -fv  # Refresh font cache

      - name: Run Python Script
        run: python app.py
