name: monthly

on:
  schedule:
    - cron: "0 6 1 * *"  # Scheduled to run at 6AM on 1st day of every month
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Specifies the runner environment
    timeout-minutes: 360

    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v3  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to latest version
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Install language fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming \
                                fonts-ipafont-mincho fonts-ipafont-gothic \
                                fonts-unfonts-core fonts-noto-cjk \
                                fonts-arabic-misc fonts-kacst ttf-wqy-zenhei
          sudo fc-cache -fv  # Refresh font cache

      - name: List installed fonts
        run: fc-list

      - name: Run Python Script
        run: python app.py
